### ISSUE TITLE
Hide by keywords don't see links

### ISSUE THREAD

**Issue by kapouik** [njelich/LinkOff#22]
**Describe the bug**
If someone use a link like #exemple, the hide by keywords feature don't match with it if you put "exemple" or "#exemple".

**To Reproduce**
Find a post that contain any internal link beginning with # and try to hide it.

**Expected behavior**
Must hide it when it match

**Screenshots**

**Environment (please complete the following information):**
 - OS: Fedora 34
 - Browser Firefox
 - Version 90.0.2

**Additional context**

**Comment by njelich** [comment]
Just tested on the latest version. Seems to be working fine with hashtags. They are part of the innerHTML, so detected correctly.
