### ISSUE TITLE
Group connections into categories + sidebars toggler, 

### ISSUE THREAD

**Issue by icetbr** [njelich/LinkOff#25]
Hi there, my desired features

- sidebars toggler, a simple hide is fine
  - alternatively, something like https://github.com/thomaswang/minimal-twitter
- make main content wider, like facebook

- group connections into categories (friends, recruiters, ...)
- show/hide feeds based on them OR mass unfollow
  https://quadlayers.com/unfollow-connections-in-bulk-linkedin/
  https://gist.github.com/brunolemos/8e13c5472b0c07d795aa766423569546

Not sure if this goes outside the scope of your plugin. If you like these ideas I can try to make a PR if I find the time :-)

**Comment by njelich** [comment]
I'm taking a look.

**Comment by njelich** [comment]
![Screen Shot 2022-03-14 at 13 41 24](https://user-images.githubusercontent.com/12912633/158174167-39272be5-23c8-4a08-bba1-63396051e7a0.png)

Some WIP on the wide mode

**Comment by njelich** [comment]
I've implemented a wide mode and mass unfollow. Grouping connections is currently out of the LinkOff development scope. @icetbr
