### ISSUE TITLE
Hide "LinkedIn News"

### ISSUE THREAD

**Issue by zmbc** [njelich/LinkOff#26]
First of all, thanks for developing this extension! It is great.

**Is your feature request related to a problem? Please describe.**
I do not know the precise name for it, but at the top right of LinkedIn is a "LinkedIn News" section which essentially represents what is trending.

**Describe the solution you'd like**
I would like to hide it. I looked for whether LinkedIn already offered a setting to turn it off, and I don't see one.

**Additional context**
![image](https://user-images.githubusercontent.com/13357648/139511189-dd7ac477-7d55-49fc-aebe-577e79f9a08f.png)

**Comment by mpaluta** [comment]
Would love this feature as well!

**Comment by njelich** [comment]
Thanks to @adamexmachina for resolving this issue :)

Closing
