### ISSUE TITLE
Hide Promoted not working

### ISSUE THREAD

**Issue by mitra42** [njelich/LinkOff#29]
**Describe the bug**
The current version does not hide promoted

**To Reproduce**
Installed extension, enabled it, 
Checked settings was Enabled and Feed/Hide-promoted was enabled

**Expected behavior**
Expected promoted items in feed not to be visible.

**Screenshots**
There seems to be no difference in the feed, promoted content is still showing (clearly marked Promoted).

**Environment (please complete the following information):**
 - OS: Mac OSX 11.6
 - Browser [e.g. chrome, safari] Firefox 94.0.2
 - Version [e.g. 22] 1.2.1 (current from the search in Firefox Add Ons)

**Additional context**

**Comment by njelich** [comment]
Tested with latest version on Macbook air, with firefox, working fine now.
