### ISSUE TITLE
Group posts and show posts of certain category.

### ISSUE THREAD

**Issue by skrish13** [njelich/LinkOff#36]
**Is your feature request related to a problem? Please describe.**
I'm frustrated since I don't have control over WHAT I see and WHEN I see it on LinkedIn.

**Describe the solution you'd like**
I would like to develop a simple solution (text analysis/ML) to group a certain number of posts (older than X days for example) into some buckets. Eg: 1) Starting a new position/job 2) Fund raising 3) Looking for job 4) Last day 5) Openings available posts etc

The ML part should be possible to a reasonable extent using JS. Before I jump in, I wanted to ask if this is feasible from UI/UX pov? Can we auto scrape all posts older than X days from the feed -> perform analysis -> show only the selected (group/category) posts. It could be mentioned that the feature will be time/resource consuming (if at all).

If you think this is even remotely possible, I would like to give it a try for my own sake 😛.

**Comment by njelich** [comment]
@skrish13 Sorry for not seeing this earlier

So, this feels like it would need to be a completely separate tool. I can point you towards development resources, but due to the way LinkedIn works it likely couldn't be real time and would require a significant overhaul of the current LinkOff setup.
