### ISSUE TITLE
Still shows liked posts 

### ISSUE THREAD

**Issue by gr4v1ty69** [njelich/LinkOff#37]
Pretty much the problem in the title. I still see liked posts by my connections with Chrome

**Comment by njelich** [comment]
Just tried, seems to be working fine.

Could you give me more information, browser, system, settings etc?

If you aren't on gentle mode it will not hide any posts until you scroll down enough to show more of them.

**Comment by gr4v1ty69** [comment]
MacOS. Chrome 100.0.4896.127. Gentle mode on or off doesn't change anything. It does hide some posts, but not the liked by connections ones. Look (aime = like in French): 
<img width="861" alt="Screen Shot 2022-04-16 at 11 59 59" src="https://user-images.githubusercontent.com/10032106/163682367-bc4340e0-b200-465d-a732-00b5c6d7ead2.png">

**Comment by gr4v1ty69** [comment]
I got why it was happening : because my LinkedIn was in FR. Only work with ENG

**Comment by njelich** [comment]
Oh man, I didn't actually think of making it available in other languages.

So, the way the filters work is that they pattern match in the post html, for the liked by etc it pattern matches the phrase in english, etc
