### ISSUE TITLE
Completely hide stuff

### ISSUE THREAD

**Issue by blimeybloke** [njelich/LinkOff#39]
I am not sure if I missed something or if this is a feature request.  First thing, this extension is AMAZING and thank you for making it.

So the question/feature I am curious about is now that I have things tweaked to show what I care about, is there a way to completely hide the stuff instead of just seeing the round minus signs?

cheers!

**Comment by njelich** [comment]
The gentle mode dims and puts the sign. If you turn it off it will simply hide. The reason that is there is due to loading behavior on LinkedIn.

You can also hide the whole feed in feed settings.
