### ISSUE TITLE
Hide creepy suggestions.

### ISSUE THREAD

**Issue by adrianos42** [njelich/LinkOff#41]
It'd be really great if you could hide the creepy "4 people from your school work here" and the "People you may also know" from the network feed.

**Comment by njelich** [comment]
I think this might be doable by adding these specific phrases to your personal custom filter. I am not sure I will be implementing them as full on options.

If you can read HTML/JS you can see how to filters work - they basically search for certain phrases. So the custom filter can be used to add any and all filters you want/need. The ones we have are simply presets. Other than that I might add better custom filter suggestions to a suggested dropdown.

Ping me if you need help figuring it out.
