### ISSUE TITLE
Un-check by default "Follow this employer" when applying to job

### ISSUE THREAD

**Issue by romanr** [njelich/LinkOff#42]
**Is your feature request related to a problem? Please describe.**
Annoying that when you apply to a job and on the last page before clicking Submit there's "Follow this employer".   
As a result you "catch" all those follows and then later wonder why you have all these companies in your feed. Yes, LinkOff may remove them but still you become involuntary follower of a lot of companies this way.

**Describe the solution you'd like**
Have the box unchecked by default.

**Additional context**
![image](https://user-images.githubusercontent.com/329079/188001226-c7f30fc6-2414-41a0-a73f-4011f1ba379a.png)

**Comment by njelich** [comment]
I think this might be resolved by using the Unfollow all action after filtering your follows by type to companies only?

**Comment by romanr** [comment]
I can't argue with this kind of logic. Yes you can go to your followings, filter out, and unfollow. Do and remember many other things manually. Not easy. Only if there was a browser extension that could help you avoid all those unnecessary operations...

**Comment by njelich** [comment]
The unfollow action automatically unfollows people
