### ISSUE TITLE
Disable LinkedIn Messages Popups

### ISSUE THREAD

**Issue by dtmunir** [njelich/LinkOff#43]
**Is your feature request related to a problem? Please describe.**
LinkedIn is a great tool but a huge memory drainer. If I'm doing some prospecting work and have a few (dozen) LinkedIn tabs open in the background, even a single new incoming LinkedIn message, causes a pop-up on every single tab, generates a ton of 'pings' and immediately hogs all the memory (in Chrome and Edge). I wish there was a way to disable the popups that LinkedIn messages generate.

**Describe the solution you'd like**
Have a toggle so that LinekdIn message pop-ups can be disabled. If there are new messages, I should have to go to the messages page to see them.

**Additional context**

<img width="1417" alt="Screen Shot 2022-09-01 at 4 12 18 PM" src="https://user-images.githubusercontent.com/707212/188013974-078148ed-753c-4518-8dd8-2374e173a2c5.png">

**Comment by njelich** [comment]
Hmm, linkoff works primarily visually. While it could disable these messages visually it probably wouldn't result in any memory savings.
