### ISSUE TITLE
Chrome "Manifest version 2 is deprecated, and support will be removed in 2023"

### ISSUE THREAD

**Issue by alfredo-f** [njelich/LinkOff#47]
When loaded in Chrome Extensions using "Load unpacked", I get the following error message

```
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
```

![image](https://user-images.githubusercontent.com/22865959/219871308-5399559a-5644-4078-93ce-80553ed83e7a.png)

**Comment by njelich** [comment]
December 9, 2022: The Manifest V2 deprecation timelines are under review and the experiments scheduled for early 2023 are being postponed. For more information, [read the update](https://groups.google.com/u/1/a/chromium.org/g/chromium-extensions/c/zQ77HkGmK9E) in the chromium-extensions Google Group.

**Comment by valdoryu** [comment]
Manifest V3 has been implemented
