### ISSUE TITLE
Hiding Carousel / Document Posts

### ISSUE THREAD

**Issue by erikmackinnon** [njelich/LinkOff#48]
**Is your feature request related to a problem? Please describe.**
LinkedIn appears to be rewarding people who are posting carousels... it's the 2023 version of last year's "poll problem."

**Describe the solution you'd like**
I'd like a setting that hides carousels entirely. (Side note: this might actually be the result of "Post a Document"?)

**Additional context**
Here's a screenshot of what I'm referring to... posts like this:

![carousel](https://user-images.githubusercontent.com/40612473/220165393-a3034879-9927-49fd-97ac-ffce5458e2be.png)

**Comment by njelich** [comment]
That should be pretty easy to add. I'll take a look at some key markers of a carousel post and make an update.

**Comment by njelich** [comment]
If you are competent, you can easily add the filter - simply find the classname/id/some other key idenitifier of carousel posts and add another hide element option.

**Comment by valdoryu** [comment]
#65 will solve this
