### ISSUE TITLE
LinkedIn css got updated, dark mode no longer works

### ISSUE THREAD

**Issue by Demopans** [njelich/LinkOff#52]
**Describe the bug**
![image](https://github.com/njelich/LinkOff/assets/22843987/2fc264b3-cb57-4535-b475-6a7eda8d6816)

**To Reproduce**
See image

**Expected behavior**
Actual dark mode

**Environment (please complete the following information):**
 - OS: Win10
 - Browser: Firefox

**Comment by njelich** [comment]
Will be removing the feature since linkedin added a dark mode.
