### ISSUE TITLE
'supports this' reactions are not filtered when 'Hide with other reactions' is selected

### ISSUE THREAD

**Issue by sofyk** [njelich/LinkOff#53]
**Describe the bug**
I have 'Hide with other reactions' selected but I still see posted with 'supports this' reactions in my feed.

**To Reproduce**
1. Enable 'Hide with other reactions'
2. go to Linkedin feed
3. observe 'supports this' reactions are not being hidden

**Expected behavior**
when 'Hide with other reactions' is enabled, posts with 'supports this' reactions should be filtered as well.

**Screenshots**
![image](https://github.com/njelich/LinkOff/assets/5036082/ce9f85ee-a8b8-443c-a96d-9709824a6b09)

**Environment (please complete the following information):**
 - OS: Windows
 - Chrome Version 120.0.6099.225 (Official Build) (64-bit)

**Additional context**

**Comment by sofyk** [comment]
understandable! thanks for the info

**Comment by valdoryu** [comment]
I can't reproduce this issue, do you still experience it @sofyk  ?

**Comment by sofyk** [comment]
not sure haven't tried it in a while. probably fixed.
