### ISSUE TITLE
Suggested posts ain't hidden

### ISSUE THREAD

**Issue by jbionic2016** [njelich/LinkOff#55]
**Is your feature request related to a problem? Please describe.**
Suggested posts are still shown in the feeds

**Describe the solution you'd like**
There must be an option to hide suggest posts

**Additional context**
See attached screenshot as evidence
![111](https://github.com/njelich/LinkOff/assets/23212486/e17ec921-d1d1-483a-98d6-50cca58d2cda)

**Comment by andrawes** [comment]
I would really love to echo this one. I love the plugin, and came to it to block these "suggested" posts. Hope you can help :)
