### ISSUE TITLE
Add job filtering

### ISSUE THREAD

**Issue by Akrai** [njelich/LinkOff#7]
So I usually search for job offers using generic terms just to avoid missing some that use different terms for the same job. So yeah, searching for generic terms brings the issue of flooding the results with unrelated results, most of which i can filter out by some very common words.

Appart from word filtering inside the jobs results i don't come up with other ideas for this section

**Comment by njelich** [comment]
LinkedIn allows boolean searches. E.g., you could add something like the following to your search string

`-senior -internship -"10+ years" -"9+ years" -"8+ years" -"7+ years" -"6+ years" -"5+ years" -"4+ years"`

**Comment by njelich** [comment]
I could however make generation of some of these a bit easier - and tie this into https://github.com/njelich/LinkOff/issues/11

**Comment by njelich** [comment]
This has been moved out of the current development scope for LinkOff, unless a contributor comes along willing to implement it.
