### ISSUE TITLE
[Feature Request] Quick Option to disable LinkOff for just 5, 10 or 15 minutes

### ISSUE THREAD

**Issue by devxbasit** [njelich/LinkOff#70]
**Is your feature request related to a problem? Please describe.**
Thank you for this awesome extension. It would be helpful if there were an option to disable it temporarily.

**Describe the solution you'd like**
option to disable LinkOff for a few minutes and automatically enable it back.

**Additional context**

**Comment by valdoryu** [comment]
Hi there

May I ask the usecase of this feature ?

**Comment by njelich** [comment]
You can manually disable it manually - these timers can be a bit tricky and wouldnt be worth it for 1 user.

**Comment by devxbasit** [comment]
@valdoryu yup, sure. Sometimes for just a quick look at "what my connection has posted" I disable the extension and get distracted for a few minutes by watching the useless videos that few of my connections have reacted or commented on(I can't remove them from my connection list). Sometimes it feels to me like I'm scrolling down on a YouTube shorts page.

@njelich Okay, no problem. For the above-mentioned thing I have raised a new issue https://github.com/njelich/LinkOff/issues/71
