### ISSUE TITLE
A feature to bypass LinkedIn login when viewing public profiles.

### ISSUE THREAD

**Issue by antony-jr** [njelich/LinkOff#9]
**Is your feature request related to a problem? Please describe.**
When viewing a public LInkedIn profile, LinkedIn will ask a login. Even if I register myself to LinkedIn it will ask a lot of personal information which is so frustrating. I'm a strong advocate of privacy and I don't want to share my personal information just to see a public profile on LinkedIn. It's gone to a point I now completely ignore linkedin profiles because of this.

**Describe the solution you'd like**
A way to hide the login prompt and clear the blur on the LinkedIn profile page.

**Additional context**
 
---

**Comment by njelich** [comment]
While LinkedIn is very strict on allowing bypasses, a dummy global account could obfuscate all this info.
Testing right now.

**Comment by njelich** [comment]
Probably running `document.cookie="li_at=AQEDATXo0x8FUomsAAABeYOogbwAAAF5p7UFvFYAriiqvXd6LTKEqOrt0idwcJxs0PWmawl7QZu9hoI-fIKH_92Es_M9MaeT0TVPO08g1WpyR0FUZepEDd_CHGrYuQYH23ZV1pJ4S8jRCZ-o51NeJ_aX"`
in certain conditions

**Comment by antony-jr** [comment]
> While LinkedIn is very strict on allowing bypasses, a dummy global account could obfuscate all this info.
Testing right now.

@njelich I will have to warn you though. When a browser extension bypasses something, it is possible that it violates Chrome Store policies, So Google might take down your add-on. 

**So my advice would be to allow a way to get this bypass from Github optionally.**

**Comment by njelich** [comment]
Prohibited Products:

    We don't allow products or services that:

        Facilitate unauthorized access to content on websites, such as circumventing paywalls or login restrictions

Yep... Sorry, this feature is not gonna happen.

**Comment by antony-jr** [comment]
Fine. I know this would happen. Anyhow Good luck on your project.

**Comment by njelich** [comment]
Btw, you can still use the above code to achieve the effect. Simply open the developer console, and run the code, then reload.

**Comment by njelich** [comment]
Actually, maybe I can create a general feature, I'll make a new feature request and tag you

**Comment by njelich** [comment]
https://github.com/njelich/LinkOff/issues/10 this should be a legal alternative, doesn't bypass, just performs autologin. might include dummy account in selector.
